### ISSUE TITLE
Dynamic Library Installation

### ISSUE THREAD

**Issue by zhanghongce** [Bo-Yuan-Huang/ILA-Tools#14]
On Ubuntu (and maybe other Linux distributions), command `ldconfig` is needed after `*.so` is copied to `/usr/local/lib/` 

For the time being I will do this manually in the installation script. But I think in the future, maybe we should include this step in CMAKE recipe or at least mention this in the README.

**Comment by Bo-Yuan-Huang** [comment]
This works fine in normal build (using the CMake recipe to build and install). 
This issue happens only if the CMake run is disabled (e.g. using pre-generated Makefile).
